server:
  port: 8001

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:users
    hikari:
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka Server 주소
  instance:
    prefer-ip-address: true # IP 주소로 등록 (호스트명 대신)