spring:
  datasource:
    url: jdbc:h2:mem:batchjob
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 20
  batch:
    jdbc:
      initialize-schema: always  # 배치 관련 테이블 자동 생성
    job:
      name: fileJob
  mail:
    host: smtp.gmail.com
    port: 587
    username: 구글아이디 #이메일은 제외해야함
    password: 발급받은 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
