spring:
  application:
    name: jpa-study
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jpa
    hikari:
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
