server:
  port: 8000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/users/**
        - id: board-service
          uri: http://localhost:8002
          predicates:
            - Path=/api/board/**
      metrics:
        enabled: true
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka Server default
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,env # 엔드포인트 지정
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
